### PR TITLE
Update capitalization of Partners HealthCare

### PR DESCRIPTION
**Pull request by mrueschman**
Based on how this is written at www.partners.org. There are many instances of "Healthcare" and not "HealthCare".

### CODE REVIEW

**Comment by mrueschman** [comment]
Hold off on this one for a few minutes; I am going to add in similar text fixes.

**Comment by mrueschman** [comment]
OK -- should be ready! @remomueller

**Comment by remomueller** [comment]
Merged into 7-0-stable, thanks!

**Comment by remomueller** [comment]
Also, looks like we may need to reload a survey from YML file to update the answer choices when we release, will create a new issue for that.

**Comment by remomueller** [comment]
Here's the associated issue #601.

**Pull request closed without merging**
